### ISSUE TITLE
Can't buy Titles

### ISSUE THREAD

**Issue by Darkfossill** [Aurilux/Titles#28]
How do you use the archive fragments to purchase titles from the archive? I have them in my inventory and it won't let me purchase any titles, just says I have 0/21, maybe I'm doing it wrong?

**Comment by Aurilux** [comment]
The wiki details how to add those fragments to the book. Specifically: "In order to add your fragments to the archive, shift-right-click with the fragments in the hotbar inventory slot to the right of the archive. If you shift-right-click with an empty slot to the right, it will spit out up to an entire stack of the fragments you have put in, that way if you manage to purchase all of the titles available, you can get your extra fragments back to turn into paper'
